# Generated by Django 4.2.5 on 2023-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_product_description_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('London', 'London'), ('Berlin', 'Berlin'), ('Amsterdam', 'Amsterdam'), ('Istanbul', 'Istanbul'), ('Montreal', 'Montreal'), ('Toronto', 'Toronto')], max_length=200, null=True),
        ),
    ]
