# Generated by Django 4.2.5 on 2023-09-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityo', models.CharField(choices=[('Delhi', 'Delhi'), ('London', 'London'), ('Berlin', 'Berlin'), ('Amsterdam', 'Amsterdam'), ('Istanbul', 'Istanbul'), ('Montreal', 'Montreal'), ('Toronto', 'Toronto')], max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
    ]
